### ISSUE TITLE
Pipelines are are not properly executed to generate Atom headers

### ISSUE THREAD

**Issue by nblock** [nblock/feeds#61]
There are two pipelines that should ensure that an ID element is present:
- AtomAutogenerateIdPipeline to generate a missing ID from the title
- AtomCheckRequiredFieldsPipeline To ensure that an ID is present

However the ID is missing for at least one generated Atom feed.

**Comment by Lukas0907** [comment]
Still happening?

**Comment by nblock** [comment]
Don't think so. I'll re-open if required.
