### ISSUE TITLE
Validate generated feeds

### ISSUE THREAD

**Issue by nblock** [nblock/feeds#62]
I just found two bugs where a previously valid Atom feed is now invalid. Tests are required to ensure that no further regressions are introduced.

**Comment by Lukas0907** [comment]
This https://github.com/rubys/feedvalidator is the tool that powers https://validator.w3.org/feed/.

However, the code is partly 10 years old and probably not compatible with Python 3.

**Comment by Lukas0907** [comment]
Invalid feeds have not been a problem for the last years. Hence I'll close this.
