### ISSUE TITLE
lxml doesn't parse certain HTML fragments properly

### ISSUE THREAD

**Issue by Lukas0907** [nblock/feeds#73]
```python
>>> import lxml
>>> lxml.html.tostring(lxml.etree.fromstring("<div class='a'><div class='b'>bar</div>baz</div>").xpath('//div[@class="b"]')[0])
b'<div class="b">bar</div>baz'
```
`baz` should clearly not be in the output.

This can happen for LWN.net articles (e.g. https://lwn.net/SubscriberLink/709561/97ea0c7b438acd3e/).

We should probably migrate to BeautifulSoup.

**Comment by nblock** [comment]
I'm fine with either library. Both are pretty common and in widespread use. AFAIK they packaged for the major Linux distributions too.

Maybe this issue should be reported to lxml?

**Comment by Lukas0907** [comment]
Reported upstream: https://bugs.launchpad.net/lxml/+bug/1662596

**Comment by Lukas0907** [comment]
Not a bug since there is ".tail". However, we should use .drop_tree() instead of getparent().remove() since drop_tree() takes care of merging the tail.
