### ISSUE TITLE
Dropped articles should not be cached

### ISSUE THREAD

**Issue by Lukas0907** [nblock/feeds#93]
Sometimes an article is dropped due to a missing field but it recovers itself, e.g. because the editor forgot something. Due to caching such self healing is not possible.

**Comment by Lukas0907** [comment]
A similar case: If a cached response leads to a 404, due to caching it will happen again as well.

**Comment by nblock** [comment]
One obvious way to "fix" this is by removing the respective cache entry: `rm -r $CACHE_DIR/$SPIDER`

**Comment by Lukas0907** [comment]
There is a signal for dropped items which could be used.
